# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
