# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_pizza_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos', verbose_name='上传图片'),
        ),
    ]
