# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_musician_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album2',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Album2',
                'proxy': True,
                'verbose_name': 'Album2',
            },
            bases=('app02.album',),
        ),
    ]
