# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 05:32
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_album2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='contents',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容'),
        ),
    ]
