# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0005_pizza_contents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'permissions': (('create_discussion', 'Can create a discussion'), ('reply_discussion', 'Can reply discussion'))},
        ),
    ]
