# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0006_auto_20180226_0555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'permissions': (('create_discussion', 'Can create a discussion'), ('create_discussion2', 'Can create a discussion2'), ('reply_discussion', 'Can reply discussion'), ('reply_discussion2', 'Can reply discussion2'))},
        ),
    ]
